sudo: required
dist: bionic
language: cpp

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install libarmadillo-dev
  - sudo apt-get -y install python3.8-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
