sudo: required
dist: bionic
language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libpython3.6-dev

install:
  - sudo apt-get -y install libarmadillo-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
