name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make build directory
      run: mkdir build
    - name: change directory
      run: cd build
    - name: run cmake
      run: cmake ..
    - name: run make
      run: make
